### ISSUE TITLE
[feature request] custom warning sound

### ISSUE THREAD

**Issue by RalphORama** [gbl/DurabilityViewer#102]
It would be cool if an advanced user could specify a sound file to use as the warning sound. Something like [TF2's hit sound customization](https://wiki.teamfortress.com/wiki/Hit_Sound).

I don't think it would have to be super complicated, maybe a text box where one could enter a [Sound ENUM](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html) value. More ambitiously, a way to choose a custom .ogg file so I could convert my TF2 hitsounds over.

**Comment by gbl** [comment]
If it isn't fancy, people will open lots of support tickets because they don't understand how to use it :(

But you can always open the jar in a zip viewer and replace the `assets/durabilityviewer/sounds/tool_breaking.ogg` file.
