### ISSUE TITLE
Position so it doesn't interfere with subtitles

### ISSUE THREAD

**Issue by kenperkins** [gbl/DurabilityViewer#12]
Minecraft 1.15.1
FabricAPI 0.4.25
Fabric Loader 0.7.2
Durability Viewer v1.15-fabric0.4.23

The UI in the corner overlays subtitles, making it tough to read them.

**Comment by gbl** [comment]
You know you can change the corner in the mod options?

If you have ModMenu (highly recommended), then you can use the gear icon to access the config. If you don't, Durability Viewer will show a book icon in the top right of the main and the pause screen.

I like the top right corner (set the option to 2), other people prefer top left (option 3), but I have the minimap there.

The problem with subtitles is the box can grow, so there's no real good position to have the viewer display above the subtitles.

**Comment by kenperkins** [comment]
I'm so sorry, I looked but didn't see anything (And I am running ModMenu). Brain fart here.
