### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by MLMII** [gbl/DurabilityViewer#13]
I was wondering if it would be feasible to add a config that would make items unable to be used once they hit their last durability?

**Comment by gbl** [comment]
Sorry, won't do that. The mod is designed to show info, but not interfere with the game in any way; for many servers this is the condition under which they allow mods at all.
This is what the breaking warner sound is intended to be for, it should give you enough time to notice and replace the item or stop using it.
Besides, it's hard to catch all edge conditions that might result in an item breaking, like right-clicking a shovel on grass or the like.
