### ISSUE TITLE
Replace armor bar with armor items

### ISSUE THREAD

**Issue by Madis0** [gbl/DurabilityViewer#14]
It would be cool to add an option that replaces the white armor bar with the actual armor items, along with their durability. The durability could probably be shown in the corner of the item, like the item count in hotbar items.

**Comment by gbl** [comment]
Sorry, I don't understand - which white armor bar? The mod should show the items with the numbers next to them?

**Comment by Madis0** [comment]
I meant the vanilla armor bar - the white/gray shirt icons. 

What if the mod hid the vanilla armor bar and showed the elements (helmet, chestplate, leggings, boots) instead?

**Comment by gbl** [comment]
But, Vanilla doesn't have an armor bar? Can you send me a screenshot of what you're talking about?

**Comment by Madis0** [comment]
https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/6/63/HUD.png/798px-HUD.png 
The white T-shirts.

**Comment by Madis0** [comment]
![image](https://user-images.githubusercontent.com/8611110/85771137-4d313e80-b724-11ea-9aec-0fc66f46e778.png)
Made a mockup to show what I mean. (ignore the hunger bar changes)
