### ISSUE TITLE
My HUD is not appearing but everything else loads fine

### ISSUE THREAD

**Issue by Southpaw1496** [gbl/DurabilityViewer#17]
So this is not an issue Per-Sae but I can't find any other support resources so I'm just putting it here.

Basically the HUD doesn't load no matter WHAT I do. I know the mod does because the thing where it shows your username at the top of the screen did load. I've tried:

 Re-installing (also deleting the config file)
2. Loading only it and the Fabric API
3. Re-downloading it about 10 times
4. Triple-checking I'm using the 1.15.2 version
In case it helps I have included a screenshot of my mods folder, my config folder and a copy of the JSON config file.
[durabilityviewer.pdf](https://github.com/gbl/DurabilityViewer/files/4251891/durabilityviewer.pdf)
![Screenshot 2020-02-25 at 7 58 56 pm](https://user-images.githubusercontent.com/44805409/75282611-4394da00-5809-11ea-8e4b-b65a5d751eb0.png)
![Screenshot 2020-02-25 at 7 59 17 pm](https://user-images.githubusercontent.com/44805409/75282653-4f809c00-5809-11ea-9f45-fca27eb440c3.png)

People always ask for my system specs so here they are even though I don't think they will help.
![Screenshot 2020-02-25 at 8 00 02 pm](https://user-images.githubusercontent.com/44805409/75282795-8e165680-5809-11ea-96ea-9efbedf4aa9d.png)

**Comment by gbl** [comment]
There's a few things that come to mind:
- Are you in creative mode? The mod doesn't show the overlay in creative mode as armor/tools are basically pointless there.
- Have you switched the HUD off? There's a key, normally h for hide, that shows/hides the HUD. Try pressing it. The key can be changed in options/controls. so make sure you didn't change it.
- Are you playing with subtitles? The config file suggests you have the HUD at the bottom right corner of the screen, where it might be hidden by subtitles. Try setting the corner to top right (set the value in line 5 of the .json file you posted to 2), does it show up then?

**Comment by Southpaw1496** [comment]
Yes I was in creative mode. There goes two hours of my life.

In my defence, it's not obvious that that is a feature at all. Perhaps you could make it a toggle, or at least put it in the Curse description.
