### ISSUE TITLE
Forge 1.15 Not working

### ISSUE THREAD

**Issue by EternalOne11** [gbl/DurabilityViewer#18]
the 1.15 forge version appears to not be functioning.

**Comment by gbl** [comment]
Any info what it is that doesn't work, any log files? I didn't test it for long, but it worked for me. Remember the default position is bottom right, you can toggle it off/on with the h button (can be configured), and it won't show anything in creative/spectator modes.

**Comment by EternalOne11** [comment]
IIt does not apear to render on the side is the problem.

**Comment by gbl** [comment]
Does the mod load at all? Can you see the keybind entry in Options/Controls? I'll need the client log file (paste it on pastebin.com and link it here) if I want to check anything.

**Comment by EternalOne11** [comment]
It works now that I pressed the keybind. It is possible it is disabled by default for some reason.
