### ISSUE TITLE
HUD location interferes with subtitles accessibility

### ISSUE THREAD

**Issue by liamgui** [gbl/DurabilityViewer#22]
This mod is unusable for those with subtitles turned on. This is an accessibility issue. Please add a feature to allow a user to change the location of the durability overlay. Or, at the very least, move it to the other side under the chat box.

**Comment by liamgui** [comment]
Also- it would be great as a release for 1.15.2 if possible!

**Comment by gbl** [comment]
There is an option to move the location of the overlay into any of the 4 corners. How to access the options depends on which loader you're using; with Fabric, there is an ingame options editor, with Forge, you need to edit the config file manually. More info on the curseforge page (https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer).

I don't really understand the request for the 1.15.2 version as there are 1.15.2 versions for Fabric as well as Forge, though? See https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer/files and make sure you get the right version for your modloader.

**Comment by gbl** [comment]
There is an option to move the location of the overlay into any of the 4 corners. How to access the options depends on which loader you're using; with Fabric, there is an ingame options editor, with Forge, you need to edit the config file manually. More info on the curseforge page (https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer).

I don't really understand the request for the 1.15.2 version as there are 1.15.2 versions for Fabric as well as Forge, though? See https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer/files and make sure you get the right version for your modloader.
