### ISSUE TITLE
Effect Duration

### ISSUE THREAD

**Issue by Darwign** [gbl/DurabilityViewer#23]
by default its yellow 
is there a way to change it's color ? I really prefer it as red or some easier to spot color
if Tooltip Color option supposed to be responsible for this then its not working or does anything else for that matter

**Comment by gbl** [comment]
Sorry, no, the color is hard coded. The tooltip color option doesn't change that; it's used to show the extended tooltip that shows durability when the MC internal debug info (F3+H) is off.

**Comment by Darwign** [comment]
You don't mind if I edit the mod to change it for my self would you ?
