### ISSUE TITLE
Annoying breaking sound

### ISSUE THREAD

**Issue by obp3ter** [gbl/DurabilityViewer#24]
Please make the breaking sound configurable, so that I don't have to edit the jar manually. Either by allowing users to disable it or a durability(value or percentage) under which is activated. I would prefer the second option.

**Comment by gbl** [comment]
There are already two options for that, one for percentage, one for value. The sound only plays when durability is below both.

**Comment by obp3ter** [comment]
I couldn't find it. Where?

**Comment by obp3ter** [comment]
I found it sorry.
