### ISSUE TITLE
I do not see the durability count on the armor or tool like for example i dont see if my pickaxe has 1000/1500 durability and i only see the weapons durability that i have in my hand

### ISSUE THREAD

**Issue by SoldierX25** [gbl/DurabilityViewer#30]

**Comment by gbl** [comment]
The mod only showing your armor and tool in hand, not other tools, is how it's intended.

But I think I don't really understand your problem. Can you add a screenshot with an explanation?

**Comment by SoldierX25** [comment]
Oh wait I see nvm
