### ISSUE TITLE
Warning in game log

### ISSUE THREAD

**Issue by linzexin022** [gbl/DurabilityViewer#32]
Hi there, I found a warning in game log:

`[16:06:52] [Thread-156/WARN]: Giselbaers Durability Viewer (durabilityviewer): java.net.UnknownHostException: raw.githubusercontent.com`

**Comment by gbl** [comment]
Maybe you were disconnected from the internet at that point?

DurabilityViewer uses ModUpdater to check for updates. This error looks like the update definition wasn't found. This doesn't affect the operation of DurabilityViewer itself though, it just means that looking for updates didn't work.
