### ISSUE TITLE
Modmenu has no cog icon for GDV, crashed when i turned off modmenu and opened cofigs from main menu

### ISSUE THREAD

**Issue by usr-pyth** [gbl/DurabilityViewer#35]

**Comment by gbl** [comment]
Without any  crash log, it's hard to say what happened. Are you sure you have the right version of the mod? CF is stupid enough to show the old weekly version in the sidebar, not the current version. For Fabric 1.16.1, you want this file:
https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer/files/2992279

**Comment by usr-pyth** [comment]
Haha, think i downloaded the snapshot! Thanks so much!
