### ISSUE TITLE
Add option to display the held item's total inventory quantity in HUD corner

### ISSUE THREAD

**Issue by bermudalocket** [gbl/DurabilityViewer#37]
It would be nice to have the option to see the total inventory count of whatever item you're holding. For example, if you need to harvest 1,900 melons, you could put a silk touch axe in your main hand and melon(s) in your offhand, which would create a counter in the bottom left corner of the screen, similar to the arrow count when holding a bow.

**Comment by Scamper10** [comment]
There are already several other mods that do this and don't conflict...
