### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by xJon** [gbl/DurabilityViewer#38]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/90807509-3fb0c300-e327-11ea-957b-f4ff80d5221c.png)
There should probably be a space there.

**Comment by gbl** [comment]
Are you sure it's my mod that adds that text? Because DurabilityViewer doesn't put a colon there at all. And also, the blue Minecraft is from some other mod. Which other mods are you using, and is that the Forge or Fabric version?

**Comment by xJon** [comment]
Hi! I'm using Forge, and the other text is from Hwyla.
I'm using color option `7`.
I can confirm it happens with no other mods.
