### ISSUE TITLE
Feature request: durability bar instead of number

### ISSUE THREAD

**Issue by xJon** [gbl/DurabilityViewer#39]
It'd be great if the option for a durability bar could be shown instead of a number, like in [CrudeDragos's Armor Bar](https://ftb.gamepedia.com/Armor_Bar):
![image](https://user-images.githubusercontent.com/8945347/90807989-ff9e1000-e327-11ea-92cf-98712b4bb562.png)
Thanks!

**Comment by xJon** [comment]
Was this supposed to be closed as `completed`, or perhaps as `not planned`?

**Comment by gbl** [comment]
Not planned, sorry. I haven't been playing Minecraft since version 1.16, and while I'm keeping the mods alive because many people have asked me to, I won't add any new features.

**Comment by xJon** [comment]
No worries, I was just referring to the (relatively new) GitHub feature of closing issues as `not planned`.
