### ISSUE TITLE
[1.16.3] Incorrect space to offhand item

### ISSUE THREAD

**Issue by realTIMematrix** [gbl/DurabilityViewer#41]
Forge: 34.0.9
durabilityviewer-1.16.2-forge33.0.5-1.8.5.jar

Issue:

If you select the option "Armor around hotbar" to "TRUE"
and select "Percentages" to "TRUE" the Chest and Helmet overlays the Offhand Item. It doesn't appear when you have nothing in the offhand but when you hold something you can't really see what you are holding.

It seems that the orientation for the armor is based on the hotbar but does not recognized the offhand item slot

<a href="https://gyazo.com/204444326601f9c5f80b148cc84ffb79"><img src="https://i.gyazo.com/204444326601f9c5f80b148cc84ffb79.png" alt="Image from Gyazo" width="906"/></a>

<a href="https://gyazo.com/d037e0fe62ec6cd3fad54d526be6bbfc"><img src="https://i.gyazo.com/d037e0fe62ec6cd3fad54d526be6bbfc.png" alt="Image from Gyazo" width="802"/></a>

**Comment by gbl** [comment]
Thanks for reporting this! Should be fixed in the newest versions (Forge and Fabric, both had the same behaviour).
