### ISSUE TITLE
Disappearing With Scoreboards

### ISSUE THREAD

**Issue by puzzlerme** [gbl/DurabilityViewer#46]
When you have a scoreboard go to the sidebar and then remove it, the durability viewer disappears and does not reappear even with restarting Minecraft or going into a different world/server

**Comment by puzzlerme** [comment]
It reappears after a while

**Comment by gbl** [comment]
Did you press the H key for some reason (or some other key you remapped the H to in Options/Controls)? That key shows/hides the durability viewer.

**Comment by puzzlerme** [comment]
Possibly lol
