### ISSUE TITLE
Game crash when I open the config page in modmenu

### ISSUE THREAD

**Issue by MarinaMarissa** [gbl/DurabilityViewer#47]
[2020-11-07-5.log](https://github.com/gbl/DurabilityViewer/files/5504761/2020-11-07-5.log)
minecraft 1.16.4
modmenu-1.14.6+build.31
fabric-api-0.25.1+build.416-1.16
fabric loader 0.10.6.214
preview_OptiFine_1.16.4_HD_U_G4_pre1
optifabric-1.8.0

**Comment by gbl** [comment]
Yep, that's an incompatibility between my config system and 1.16.4. Will update on CF this weekend after a few more tests.

In the meantime, you can try this version here: https://github.com/gbl/DurabilityViewer/releases/tag/1.16.4-1.9pre
