### ISSUE TITLE
Feature Request: allow configuring a notification instead of a sound

### ISSUE THREAD

**Issue by campbebj** [gbl/DurabilityViewer#49]
Players who dont or cant play with sound cant take advantage of the audio notification when the item is breaking. 

Is there a way to show a visual notification either as text or a popup (sorta like advancements)?

**Comment by gbl** [comment]
In the newest version 1.10, there is! Just uploaded to CF, let's hope they approve it soon.
Or you can download from Modrinth here: https://modrinth.com/mod/LTM1f0yY
