### ISSUE TITLE
durabilityviewer-1.14-fabric0.2.7-1.5.jar has a mcmod.info file in it

### ISSUE THREAD

**Issue by calloatti** [gbl/DurabilityViewer#5]
durabilityviewer-1.14-fabric0.2.7-1.5.jar  has a  mcmod.info file inside. It does nothing I guess, except that it breaks my updater.

**Comment by gbl** [comment]
Fixed in version 1.6, the mcmod.info is gone now. It was a leftover from the Forge version.
