### ISSUE TITLE
1.12 - 1.6 No way to disable warning sound

### ISSUE THREAD

**Issue by kreezxil** [gbl/DurabilityViewer#50]
You have it so that I can control when it happens, but I would like the option to mute that sound too. What I like most about the mod is being able to see my tools and armor quickly at a glance on the main HUD. The item durability warning, I can live without, so an option to disable it would be great.

**Comment by gbl** [comment]
The newest version can do that - you can switch the warning between sound only, visual only, both, or none.

**Comment by kreezxil** [comment]
my pack is 1.12.2 tho. i have the newest version, did you just upload? is there a 1.12.2 1.7 now?

**Comment by gbl** [comment]
Ah, sorry, I didn't see you're still back at 1.12.

Sorry, but I won't backport features to those old versions, that's just too much work for too few users. (The source code is available though so everybody is welcome to do it themselves).

However, that version already has the "minimum percent" and "minimum durability" options. If you set both of them to 1, you'll get a single ripping sound when something breaks, but nothing else (and you can even disable that by removing the ogg file from the jar as described at the end of the curseforge text)

**Comment by kreezxil** [comment]
Except I use this in a public pack. My pack World of Dragons. If I were to
do what you suggest I would have to release a "Reloaded" version of the
mod. If I were running a private pack that wasn't publicly distributed, I
would do as you suggest.
