### ISSUE TITLE
Color Doesn't Change

### ISSUE THREAD

**Issue by jordanzz** [gbl/DurabilityViewer#51]
I tried to change the color of the durability numbers and it doesn't. The menu shows the correct color I have chosen, but the default green color still stays on the hud.

**Comment by gbl** [comment]
The HUD colors are fixed, they can't be changed. The config color selection is about the tooltip extension, marked in purple here:

![image](https://user-images.githubusercontent.com/243563/104089778-e57eb300-5271-11eb-94c3-edb8be43bdbb.png)

**Comment by jordanzz** [comment]
Alright thanks for the answer
