### ISSUE TITLE
[Suggestion] blacklisting gear from durability pings

### ISSUE THREAD

**Issue by ghost** [gbl/DurabilityViewer#52]
if i create a new world and use some stone tools, the quite common durability pings get annoying quickly, especially because i usually just use up my early game tools until they break and make new ones.

**Comment by magnus-ISU** [comment]
Also applies to stone swords, gold swords, crossbows, iron axes, etc dropped from wither skeletons, piglins, and pillagers. It confused me a lot when I first encountered it.

A potential solution that requires less manual player configuration too would be an option to require that a tool has mending on it to warn you about durability - I don't typically repair things that I haven't put mending onto.
