### ISSUE TITLE
Negative Durability 

### ISSUE THREAD

**Issue by Lucas-Rosenzweig** [gbl/DurabilityViewer#53]
Hi, I have a problem, the mod displays me negative durability instead of the actual durability of the armor or items
![2021-03-09_18 12 47](https://user-images.githubusercontent.com/38187137/110510116-2a548800-8103-11eb-8b06-ff09024bf8d9.png)

**Comment by gbl** [comment]
Yes. That's what the "Percent to show damage" option is for. Set it to 100% to always show remaining durability, 0% to always shows what's missing to full repair. Default is 80%, so for netherite items that have approx. 2000 total, it'll go from 0 to -400 first, then from 1600 to 0.

**Comment by Lucas-Rosenzweig** [comment]
Thanks sorry for that x)
