### ISSUE TITLE
Durability count is wrong

### ISSUE THREAD

**Issue by SkyTheNerd** [gbl/DurabilityViewer#56]
I watched my friend play Minecraft and it said that his fishing rod was 2 durability, but when he used it, it broke, so he asked me to complain lol.

**Comment by gbl** [comment]
From https://minecraft.fandom.com/wiki/Durability:

Fishing rods:

- Breaking a block or hitting a mob counts as 0 uses.
- Casting the line and reeling it in empty, counts as 0 uses.
- Reeling in an item counts as 1 use.
- Catching the bobber/hook on a block, then reeling it in, counts as 2 uses.
- Using the line to yank on an item counts as 3 uses.
- Using the line to yank on a mob counts as 5 uses.
