### ISSUE TITLE
[1.16.5 Forge] Icons render in front of chat

### ISSUE THREAD

**Issue by ocram9** [gbl/DurabilityViewer#57]
As the title says, the icons render in front of the chat when the HUD is in the bottom left corner (see screenshot).

![Screenshot_15](https://user-images.githubusercontent.com/49008532/118024350-df532d00-b35e-11eb-84f2-b673e5acb2e1.png)

Forge 31.1.16
DurabilityViewer: 1.16.4-forge35.0.7-1.10

**Comment by catgirldoll** [comment]
To add to this, bottom right HUD renders in front of subtitles. Being able to offset the HUD horizontally would help prevent both issues.
