### ISSUE TITLE
A Red Bugg or Error?

### ISSUE THREAD

**Issue by MrFreakOne** [gbl/DurabilityViewer#63]
Hello,

_"Translated into English with google.com"._

i want to point out a little red bug. I don't know what that means, but I assume that your mod is made for Minecraft version 1.16.4 and that's why this red error appears. I would love to know when you will upgrade your mod please. It is a really, very good and helpful mod.

![Durability Viewer](https://user-images.githubusercontent.com/53281959/144297374-ad57e334-daec-4bb0-8691-5b28d6bab972.jpg)

See you.    👍

**Comment by gbl** [comment]
I don't know where you got it from, but both official distribution points, modrinth and curseforge, have versions for 1.17 and 1.18:

https://modrinth.com/mod/durabilityviewer/versions

https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer/files

As you seem to be using Forge, make sure you download the Forge version, not the Fabric version. And Forge for 1.18 doesn't exist yet, so there's only a 1.17 version now.

And please use Modrinth or Curseforge to download, these are the only two sites that have the files officially from me. Everything else is stolen and not updated by me.
