### ISSUE TITLE
[1.18.1 Fabric] DurabilityViewer cannot be loaded (it says "install Fabric")

### ISSUE THREAD

**Issue by Sethxity** [gbl/DurabilityViewer#65]
Please discard this post if the version for 1.18.1 is in WIP.

I could not launch DurabilityViewer under Minecraft version 1.18.1, Fabric Loader version 0.12.11. It says, "Install fabric, any version". Logs link below. 
https://paste.ee/p/V6plo

Logs for the same instance without any mods are below. It launches successfully. 
https://paste.ee/p/RORCv
I can fire up Minecraft in this Fabric version with Sodium + Iris, so Fabric Loader itself is not the issue, I think.

I hope the logs I posted will help with the 1.18.1 version development. Thank you.

**Comment by gbl** [comment]
You also need the Fabric API! 
https://modrinth.com/mod/fabric-api/versions
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files

**Comment by Sethxity** [comment]
Ah, I see, thank you.

P.S. I think it will be better for Fabric API requirements to be written on the Mod page description. Some Fabric mods don't require Fabric API, and mods that need the API mostly have it written on the description page.
