### ISSUE TITLE
Durability Viewer interferes with subtitles 

### ISSUE THREAD

**Issue by Pectacular** [gbl/DurabilityViewer#66]
When subtitles are enabled and a sound plays, the subtitles interfere with the HUD of this mod. It would be nice if the subtitles are moved up when the HUD is enabled.

**Comment by Pectacular** [comment]
Here is a screenshot for reference -
![Uploading 2021-12-14_14.58.22.png…]()

**Comment by gbl** [comment]
If you have subtitles on, the bottom right corner obviously isn't a good place for the HUD. Just move it to any of the other corners.

**Comment by Pectacular** [comment]
Sorry didn't check the config
