### ISSUE TITLE
Fix compatibility with 1.18.2

### ISSUE THREAD

**Issue by giorov** [gbl/DurabilityViewer#69]
CTD [crash-2022-03-05_14.00.26-client.txt](https://github.com/gbl/DurabilityViewer/files/8191559/crash-2022-03-05_14.00.26-client.txt)

**Comment by giorov** [comment]
[NightEule5](https://github.com/NightEule5) commented https://github.com/LambdAurora/LambdaBetterGrass/issues/45#issuecomment-1061321650 "The mixin for net.minecraft.class_3304 which maps to net.minecraft.resource.ReloadableResourceManagerImpl is failing. The method method_14475, which maps to addPack in 1.18.1, is missing from 1.18.2's mappings. It must've been removed"

No idea if that is helpful or if it's a confabricate dependancy or what.

**Comment by triphora** [comment]
https://cdn.discordapp.com/attachments/745979270748307458/951938158893858876/crowdin-translate-1.41.18.2.jar

Drop this in your mods folder alongside the latest DurabilityViewer release and it will work fine.

**Comment by gbl** [comment]
Updated version for 1.18.2 pushed to CF and Modrinth. And thank you to wafflecoffee for producing an intermediate version!
