### ISSUE TITLE
Question: hide chest and tool icons

### ISSUE THREAD

**Issue by sepsol** [gbl/DurabilityViewer#72]
Is it possible to other than the chest, to also hide the other icons on the lower right corner (default) of the screen? I only want to view the durability of my armor around the hotbar.

**Comment by magnus-ISU** [comment]
It is. Idk how I did it exactly but I know I have this

**Comment by magnus-ISU** [comment]
I'm making a fork which also hides armor if they're above certain durability (with the intent to upstream it, I have the code working just need to clean it up), I'll take a look at this again in a bit.

**Comment by magnus-ISU** [comment]
Nevermind I lied. I can add this to my fork, though, it shouldn't be hard.

**Comment by magnus-ISU** [comment]
Added in #75

**Comment by magnus-ISU** [comment]
A binary can be found [here](https://github.com/magnus-ISU/clientside-mods/blob/master/mods/durabilityviewer-1.19-fabric0.53.3-1.10.3.jar) in case anyone *really* wants this feature
