### ISSUE TITLE
Unable to disable audible durability warning

### ISSUE THREAD

**Issue by astridellensdottir** [gbl/DurabilityViewer#79]
I mostly want to have durability numbers visible on-screen, and the warning is both loud and jarring when i've disabled it through the mod's options.

**Comment by astridellensdottir** [comment]
update; restarting the game after setting the "warning mode" option to "none" disabled the sound, but it only took effect after restarting the game.

**Comment by gbl** [comment]
This should work, normally. You need to exit the options screen with the button, though, pressing ESC will not work. Maybe you did that?
