### ISSUE TITLE
"Armor around hotbar" mode obstructs shield inventory icon

### ISSUE THREAD

**Issue by MrNiceforest** [gbl/DurabilityViewer#8]
When having an item in the shield slot equipped and "Armor around hotbar" mode enabled the armor display will obstruct the hotbar icon for shield slot, see below. (This was also present in MC v1.14.3, so I believe it's not related to MC v1.14.4)

durabilityviewer-1.14-fabric0.2.7-1.5
Minecraft: v1.14.4 release
Fabric: v0.4.8-build 158

![2019-07-29_20 22 18](https://user-images.githubusercontent.com/30006052/62072561-372eab80-b23f-11e9-875a-42b54ab513c2.jpg)

**Comment by gbl** [comment]
Fixed in version 1.6.
