### ISSUE TITLE
1.19.4 -  Compatibility

### ISSUE THREAD

**Issue by wilebaldo** [gbl/DurabilityViewer#84]
I just read on courseforge you said this mod is not coming more updates, and I understand. But I would like to help with that if is possible. I'm not expert programing but I'm lerning and I would like try to make a port or just change whatever is need to be compatibity with the new version. you thing is possible I can try work with your mod? all the necessary files in this GitHub is available to do?

**Comment by votommy** [comment]
This has the MIT license, which means you DO have permission to modify the code.
