### ISSUE TITLE
 Giselbaer's Durability Viewer crashes on Minecraft v1.20.1

### ISSUE THREAD

**Issue by MelchiorGaspar** [gbl/DurabilityViewer#88]
crashed, durabilityviewer-1.20-fabric0.83.0-1.10.4.jar

using Fabric Loader version, v0.14.21
using Fabric API version, fabric-api-0.84.0+1.20.1.jar

crash log attached.
[crash-2023-06-28_15.16.38-client.txt](https://github.com/gbl/DurabilityViewer/files/11899281/crash-2023-06-28_15.16.38-client.txt)

hope that helps narrow down the issue/bug... 
thx for keeping the mod going.. its an essential mod to have lol :D ^_^

**Comment by gbl** [comment]
Please add cloth config. from https://modrinth.com/mod/cloth-config or https://www.curseforge.com/minecraft/mc-mods/cloth-config. Not sure what's wrong here as it is listed as a dependency and there should have been a message saying it's missing.

**Comment by MelchiorGaspar** [comment]
ooh ok, yeah Cloth config, 
I had that installed for a mod before.. 
I got rid of it because another older mod got updated that didn't use it.
thx for letting me know.. grabbed it and now testing it out.

cmdkeybind-1.6.3-1.20.jar, is the mod I now using for macros again, since it is back to being updated..
and the other one I had for a little while used cloth config.

**Comment by MelchiorGaspar** [comment]
ok its working now, no crashing..
thx for the info/tip.

**Comment by xenouch** [comment]
Have same crash with 1.20.1

Already installed "cloth config" from [https://modrinth.com/mod/cloth-config](url)

using Fabric Loader version, v0.14.21
using Fabric API version, fabric-api-0.85.0+1.20.1.jar

[crash-2023-07-05_08.13.14-client.txt](https://github.com/gbl/DurabilityViewer/files/11954426/crash-2023-07-05_08.13.14-client.txt)
