### ISSUE TITLE
debug.log spam

### ISSUE THREAD

**Issue by SlayerTheChikken** [gbl/DurabilityViewer#96]
In the 1.19.2 version of the mod (at the very least) durability viewer spams the debug.log with millions of 

```
[23:29:20] [Render thread/DEBUG] (de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability) trinket position 0 has item air

[23:29:20] [Render thread/DEBUG] (de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability) trinket position 1 has item air

[23:29:20] [Render thread/DEBUG] (de.guntram.mcmod.durabilityviewer.client.gui.GuiItemDurability) trinket position 2 has item air
```

lines causing the file size to inflate to hundreds of MBs or more the longer you play, currently in 5 minutes or so it reaches 100MB. 

I will do more research into if it's this mod or another interacting with it (other than trinkets.)

**Comment by SlayerTheChikken** [comment]
Okay so with this mod, trinkets, and debug logging enabled the behavior still occurs; it just gets worse the more trinket mods that are installed.

My only question is if this is intended behavior? If so I can close this issue and disable debug logging, the only concern is SSDs getting pooped from stuff like this (though it wouldn't happen with debug logging disabled so...)

**Comment by SlayerTheChikken** [comment]
I'm just going to guess this is intended behavior but I wanted to be safe, just let me know to close the issue <3

**Comment by gbl** [comment]
It's (kind of) intended behavior, when I added trinkets compatibility to DurabilityViewer, I got some crashes that I needed to debug, so I added some debug log spam.  Normally that doesn't get output at all, so it's no problem, and if you use the normal log4j config file, you can set the log level per class (so, per mod), so you can have debug enabled for the mod you want to debug but not for others. Which again makes it no problem.

The message basically says "there's a trinket slot that doesn't have a trinket in it', so yes, the more empty trinket slots you have, the more spam you get.

Of course, if you use a mod to enable debug level globally, as you seem to do, you'll get the spam all the time. In my opinion, it doesn't make sense to enable the debug log unless you're a developer trying to fix a specific problem, so, not enabling debug by default (or at least provide that option) would make sense in the mod you're using.
